#!/usr/bin/env ansible-playbook
---

- debug: msg="==> setting for Nginx"

# backup default nginx virtualhost.
- name: check if "default.conf.bak" target exists
  stat: path=/etc/nginx/conf.d/default.conf
  register: filecheck

- name: rename to "default.conf.bak", if any
  command: mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.bak
  when: filecheck.stat.exists
  notify: restart nginx

# add new nginx virtualhost.
- name: add testlink virtualhost of nginx
  vars:
    php_socket_path: /var/run/php/php7.0-fpm.sock
  template:
    src: ./templates/nginx-testlink.conf.j2
    dest: /etc/nginx/conf.d/nginx-testlink.conf
  notify: restart nginx

# vim:ft=ansible :
