#!/usr/bin/env ansible-playbook

---
- name: deploy testlink with chusiang.testlink role
  hosts: all
  become: true

  roles:
    - williamyeh.nginx
    - chusiang.php7
    - geerlingguy.mysql
    - chusiang.testlink

  tasks:
    - name: include check task
      include: roles/chusiang.testlink/tasks/check.yml

  post_tasks:
    # Run some tests.
    - include: roles/chusiang.testlink/tests/curl_testlink_web.yml

# vim:ft=ansible:
