#!/usr/bin/env ansible-playbook
---

- name: Send notification to Slack
  hosts: localhost

  vars:
    slack_domain: 'example.slack.com'
    slack_token: 'xxxxxxxxxxxxxxxxxxxxxxxx'
    slack_channel: "@username"

  post_tasks:
    - name: send notification to slack
      slack:
        domain: "{{ slack_domain }}"
        token: "{{ slack_token }}"
        username: "ansible"
        channel: "{{ slack_channel }}"
        color: "normal"
        msg: "Send a notification with Ansible !"

# vim: ft=ansible :
